version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    ECR_ACCOUNT: 795974654805
    ECR_REPO: brain-tasks-app
    CLUSTER_NAME: brain-eks
    IMAGE_TAG: latest

phases:
  install:
    commands:
      - echo Installing kubectl...
      - curl -LO https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/kubectl
      - kubectl version --client

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION |
        docker login --username AWS --password-stdin $ECR_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig \
        --region $AWS_REGION \
        --name $CLUSTER_NAME \
        --role-arn arn:aws:iam::795974654805:role/service-role/codebuild-brain-tasks-codebuild-service-role       

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $ECR_REPO .
      - docker tag $ECR_REPO:latest $ECR_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $ECR_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
      - echo Deploying to EKS...
      - kubectl apply -f k8s/
      - kubectl rollout status deployment/brain-tasks-deployment
      - kubectl get ns

